workflows:
  ios-testflight:
    name: iOS to TestFlight (Auto-Sign)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      groups:
        - appstore_credentials
      vars:
        BUNDLE_ID: "com.leisureryde.ryde"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        IOS_DEPLOYMENT_TARGET: "14.0"
        APPLE_TEAM_ID: $apple_team_id

      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Patch Podfile to enforce iOS 14.0
        script: |
          PODFILE="ios/Podfile"
          if [ ! -f "$PODFILE" ]; then
            (cd ios && pod init)
          fi

          cat >> "$PODFILE" <<EOF

# === FORCE ALL PODS TO iOS 14.0 ===
  post_install do |installer|
  installer.pods_project.targets.each do |target|
  flutter_additional_ios_build_settings(target)
  target.build_configurations.each do |config|
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
  end
  end
  end
  EOF
  
  echo "Podfile patched with post_install hook"

- name: Install CocoaPods
  script: |
    cd ios
    pod repo update
    pod install --verbose

- name: Set Xcode deployment target
  script: |
    /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 14.0" ios/Runner/Info.plist 2>/dev/null \
      || /usr/libexec/PlistBuddy -c "Add :MinimumOSVersion string 14.0" ios/Runner/Info.plist

- name: Archive and Export IPA
  script: |
    ARCHIVE_PATH="$CM_BUILD_DIR/Runner.xcarchive"
    IPA_PATH="$CM_BUILD_DIR/ipa"
    
    cat > ios/exportOptions.plist <<EOF
  <?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
  <dict>
  <key>method</key><string>app-store</string>
  <key>signingStyle</key><string>automatic</string>
  <key>teamID</key><string>$APPLE_TEAM_ID</string>
  <key>uploadSymbols</key><true/>
  </dict>
  </plist>
  EOF
  
  xcodebuild -workspace "ios/$XCODE_WORKSPACE" \
  -scheme "$XCODE_SCHEME" \
  -archivePath "$ARCHIVE_PATH" \
  DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
  CODE_SIGN_STYLE=automatic \
  archive
  
  xcodebuild -archivePath "$ARCHIVE_PATH" \
  -exportArchive \
  -exportOptionsPlist ios/exportOptions.plist \
  -exportPath "$IPA_PATH" \
  -allowProvisioningUpdates

artifacts:
  - $CM_BUILD_DIR/ipa/*.ipa

publishing:
  email:
    recipients:
      - "Ibraheemakin201@gmail.com"

  app_store_connect:
    api_key: $APP_STORE_CONNECT_PRIVATE_KEY
    key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
    issuer_id: $APP_STORE_CONNECT_ISSUER_ID
    submit_to_testflight: true