workflows:
  build_ios_only:
    name: Build & Upload iOS App to TestFlight (Automatic Signing)
    environment:
      groups:
        - appstore_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "LeisureRyde"
        BUNDLE_ID: "com.leisureryde.ryde"
        APP_STORE_TEAM_ID: "S8LF4BM9D3"   # ðŸ‘ˆ your real Apple Team ID

    scripts:
      - name: Clean project & install dependencies
        script: |
          echo "ðŸ§¹ Cleaning Flutter project..."
          flutter clean || true
          flutter pub get || true

      - name: Ensure Podfile exists and iOS platform >= 14.0
        script: |
          echo "ðŸ›  Ensuring Podfile and platform version..."
          if [ ! -f "ios/Podfile" ]; then
            cd ios
            pod init
            cd ..
          fi
          sed -i '' 's/platform :ios.*/platform :ios, '\''14.0'\''/' ios/Podfile || true

      - name: Install CocoaPods dependencies
        script: |
          echo "ðŸ“¦ Installing iOS pods..."
          cd ios
          pod repo update || true
          pod install || true
          cd ..

      - name: Enable automatic signing
        script: |
          echo "ðŸ” Enabling automatic signing for $BUNDLE_ID ..."
          xcode-project use-profiles --team-id $APP_STORE_TEAM_ID --automatic-signing

      - name: Build iOS IPA for TestFlight
        script: |
          echo "ðŸŽ Building iOS IPA..."
          mkdir -p ios
          cat > ios/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>teamID</key>
              <string>$APP_STORE_TEAM_ID</string>
              <key>destination</key>
              <string>export</string>
              <key>compileBitcode</key>
              <false/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF

          flutter build ios --release --no-codesign
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --export-options-plist ios/exportOptions.plist \
            --team-id $APP_STORE_TEAM_ID \
            --automatic-signing

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "Ibraheemakin201@gmail.com"
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
