workflows:
  build_and_test:
    name: Build Android & iOS for TestFlight
    environment:
      groups:
        - appstore_credentials    # Group where you stored API keys
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "LeisureRyde"
        BUNDLE_ID: "com.leisureryde.app"

    scripts:
      - name: Clean and get dependencies
        script: |
          echo "🧹 Cleaning project..."
          flutter clean || true
          flutter pub get || true

      - name: Analyze code (ignore errors)
        script: |
          echo "🔍 Analyzing code..."
          flutter analyze || true

      - name: Build Android APK (ignore build errors)
        script: |
          echo "🤖 Building Android APK..."
          flutter build apk --release || true

      - name: Build iOS IPA (automatic signing, ignore build errors)
        script: |
          echo "🍎 Building iOS IPA..."
          mkdir -p ios
          cat > ios/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>destination</key>
              <string>export</string>
              <key>compileBitcode</key>
              <false/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF

          flutter build ios --release --no-codesign || true
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --export-options-plist ios/exportOptions.plist || true

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "Ibraheemakin201@gmail.com"
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
