workflows:
  ios-testflight:
    name: iOS to TestFlight (Auto Podfile)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      groups:
        - appstore_credentials
      vars:
        BUNDLE_ID: "com.leisureryde.ride"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        IOS_DEPLOYMENT_TARGET: "14.0"
        APPLE_TEAM_ID: $apple_team_id

      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Ensure Podfile exists and set iOS 14.0
        script: |
          echo "ðŸ“± Checking Podfile..."
          cd ios
          if [ ! -f "Podfile" ]; then
            echo "âš™ï¸ No Podfile found. Creating one..."
            pod init
          fi

          # Ensure platform :ios, '14.0'
          if grep -q "platform :ios" Podfile; then
            sed -i '' "s/platform :ios.*/platform :ios, '14.0'/" Podfile
          else
            echo "platform :ios, '14.0'" >> Podfile
          fi
          cd ..

      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Build and export IPA
        script: |
          ARCHIVE_PATH="$CM_BUILD_DIR/Runner.xcarchive"
          IPA_PATH="$CM_BUILD_DIR/ipa"

          xcodebuild -workspace "ios/$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "$ARCHIVE_PATH" \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            CODE_SIGN_STYLE=Automatic \
            archive

          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath "$IPA_PATH" \
            -allowProvisioningUpdates

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      email:
        recipients:
          - "Ibraheemakin201@gmail.com"
