workflows:
  build_and_test:
    name: Build Android & iOS for Testing
    environment:
      groups:
        - appstore_credentials    # ðŸ‘ˆ Add this group with your App Store Connect API details
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "LeisureRyde"
        BUNDLE_ID: "com.leisureryde.app"

    scripts:
      - name: Clean and get dependencies
        script: |
          echo "ðŸ§¹ Cleaning project..."
          flutter clean || true
          flutter pub get || true

      - name: Analyze code (ignore errors)
        script: |
          echo "ðŸ” Running static analysis (will ignore errors)..."
          flutter analyze || true

      - name: Build Android APK (ignore build errors)
        script: |
          echo "ðŸ¤– Building Android release APK..."
          flutter build apk --release || true

      - name: Build iOS IPA (automatic signing, ignore errors)
        script: |
          echo "ðŸŽ Building iOS release IPA..."
          mkdir -p ios
          cat > ios/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>destination</key>
              <string>export</string>
          </dict>
          </plist>
          EOF

          flutter build ios --release --no-codesign || true
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --archive-path build/Runner.xcarchive \
            --export-options-plist ios/exportOptions.plist || true

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "Ibraheemakin201@gmail.com"
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
