workflows:
  build_ios_only:
    name: Build & Upload iOS App to TestFlight (Automatic Signing)
    environment:
      groups:
        - appstore_credentials      # 👈 Must include your App Store API key vars
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "LeisureRyde"
        BUNDLE_ID: "com.leisureryde.ios"
        APP_STORE_TEAM_ID: "S8LF4BM9D3"   # 👈 Replace with your real Apple Team ID

    scripts:
      - name: Clean project & install dependencies
        script: |
          echo "🧹 Cleaning Flutter project..."
          flutter clean || true
          flutter pub get || true

      - name: Ensure Podfile exists and iOS platform >= 14.0
        script: |
          echo "🛠 Ensuring Podfile and platform version..."
          if [ ! -f "ios/Podfile" ]; then
            cd ios
            pod init
            cd ..
          fi
          sed -i '' 's/platform :ios.*/platform :ios, '\''14.0'\''/' ios/Podfile || true

      - name: Install CocoaPods dependencies
        script: |
          echo "📦 Installing iOS pods..."
          cd ios
          pod repo update || true
          pod install || true
          cd ..

      - name: Enable automatic signing
        script: |
          echo "🔐 Enabling automatic signing for $BUNDLE_ID ..."
          xcode-project use-profiles \
            --bundle-id $BUNDLE_ID \
            --team-id $APP_STORE_TEAM_ID \
            --signing-style automatic || true

      - name: Build iOS IPA (auto-signing)
        script: |
          echo "🍎 Building iOS IPA for TestFlight..."
          mkdir -p ios
          cat > ios/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>destination</key>
              <string>export</string>
              <key>compileBitcode</key>
              <false/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF

          flutter build ios --release --no-codesign
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --team-id $APP_STORE_TEAM_ID \
            --automatic-signing \
            --export-options-plist ios/exportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "Ibraheemakin201@gmail.com"
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
