workflows:
  flutter-test-build:
    name: Flutter Test Build (Android + iOS)
    max_build_duration: 60
    instance_type: mac_mini_m1

    environment:
      flutter: stable
      xcode: latest
      java: 17
      cocoapods: default
      groups:
        - app_store_credentials   # Apple API key group
      vars:
        APP_NAME: "MyFlutterApp"

    cache:
      cache_paths:
        - ~/.pub-cache
        - build

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Analyze project (ignore warnings & errors)
        script: |
          echo "Analyzing project..."
          flutter analyze || true

      - name: Run tests (ignore failures)
        script: |
          echo "Running tests..."
          flutter test || true

      - name: Build Android APK (release)
        script: |
          echo "Building Android release APK..."
          flutter build apk --release || true

      - name: Build iOS IPA (release)
        script: |
          echo "Building iOS release IPA..."
          flutter build ipa --release \
            --export-options-plist=export_options.plist || true

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - Ibraheemakin201@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
