workflows:
  build_and_test:
    name: Build Android & iOS for TestFlight (Auto Signing)
    environment:
      groups:
        - appstore_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "LeisureRyde"
        BUNDLE_ID: "com.leisureryde.app"
        APP_STORE_TEAM_ID: "S8LF4BM9D3"   # ðŸ‘ˆ Replace this with your real Apple Team ID

    scripts:
      - name: Clean and get dependencies
        script: |
          echo "ðŸ§¹ Cleaning project..."
          flutter clean || true
          flutter pub get || true

      - name: Ensure Podfile exists and set platform
        script: |
          echo "ðŸ›  Ensuring Podfile exists..."
          if [ ! -f "ios/Podfile" ]; then
            cd ios
            pod init
            cd ..
          fi
          echo "ðŸ“± Ensuring iOS platform >= 14.0"
          sed -i '' 's/platform :ios.*/platform :ios, '\''14.0'\''/' ios/Podfile || true

      - name: Install CocoaPods
        script: |
          echo "ðŸ“¦ Installing pods..."
          cd ios
          pod repo update || true
          pod install || true
          cd ..

      - name: Enable automatic signing
        script: |
          echo "ðŸ” Enabling automatic signing for $BUNDLE_ID ..."
          xcode-project use-profiles \
            --bundle-id $BUNDLE_ID \
            --team-id $APP_STORE_TEAM_ID \
            --signing-style automatic || true

      - name: Build Android APK
        script: |
          echo "ðŸ¤– Building Android..."
          flutter build apk --release || true

      - name: Build iOS IPA (automatic signing, ignore errors)
        script: |
          echo "ðŸŽ Building iOS IPA..."
          mkdir -p ios
          cat > ios/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>destination</key>
              <string>export</string>
              <key>compileBitcode</key>
              <false/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF

          flutter build ios --release --no-codesign || true
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --export-options-plist ios/exportOptions.plist || true

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "Ibraheemakin201@gmail.com"
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
