workflows:
  ios-testflight:
    name: iOS to TestFlight
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      groups:
        - appstore_credentials
      vars:
        BUNDLE_ID: "com.leisureryde.ride"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APPLE_TEAM_ID: $apple_team_id
        IOS_DEPLOYMENT_TARGET: "14.0"

      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: 'main'
          include: true
        - pattern: 'release/*'
          include: true

    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          echo "📦 Installing CocoaPods..."
          cd ios
          pod repo update
          pod install --verbose
          cd ..

      - name: Set iOS deployment target in Info.plist
        script: |
          echo "📝 Setting MinimumOSVersion to ${IOS_DEPLOYMENT_TARGET} in Info.plist"
          /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion ${IOS_DEPLOYMENT_TARGET}" ios/Runner/Info.plist 2>/dev/null \
          || /usr/libexec/PlistBuddy -c "Add :MinimumOSVersion string ${IOS_DEPLOYMENT_TARGET}" ios/Runner/Info.plist

      - name: Archive and Export IPA
        script: |
          ARCHIVE_PATH="$CM_BUILD_DIR/Runner.xcarchive"
          IPA_PATH="$CM_BUILD_DIR/ipa"
          
          # Create exportOptions.plist for automatic signing
          cat > ios/exportOptions.plist <<EOF
  <?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
  <dict>
  <key>method</key><string>app-store</string>
  <key>signingStyle</key><string>automatic</string>
  <key>teamID</key><string>${APPLE_TEAM_ID}</string>
  <key>uploadSymbols</key><true/>
  </dict>
  </plist>
  EOF
  
  # Archive the app
  xcodebuild -workspace "ios/${XCODE_WORKSPACE}" \
  -scheme "${XCODE_SCHEME}" \
  -archivePath "${ARCHIVE_PATH}" \
  DEVELOPMENT_TEAM="${APPLE_TEAM_ID}" \
  CODE_SIGN_STYLE=Automatic \
  -allowProvisioningUpdates \
  archive
  
  # Export IPA
  xcodebuild -archivePath "${ARCHIVE_PATH}" \
  -exportArchive \
  -exportOptionsPlist ios/exportOptions.plist \
  -exportPath "${IPA_PATH}" \
  -allowProvisioningUpdates

artifacts:
  - $CM_BUILD_DIR/ipa/*.ipa

publishing:
  email:
    recipients:
      - "Ibraheemakin201@gmail.com"

  app_store_connect:
    api_key: $APP_STORE_CONNECT_PRIVATE_KEY
    key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
    issuer_id: $APP_STORE_CONNECT_ISSUER_ID
    submit_to_testflight: true
