workflows:
  build_ios_only:
    name: Build & Upload iOS App to TestFlight
    environment:
      groups:
        - appstore_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_NAME: "LeisureRyde"
        BUNDLE_ID: "com.leisureryde.ryde"
        APP_STORE_TEAM_ID: "S8LF4BM9D3"   # Your Apple Team ID

    scripts:
      - name: Clean project & install dependencies
        script: |
          echo "🧹 Cleaning Flutter project..."
          flutter clean || true
          flutter pub get || true

      - name: Ensure Podfile and platform >= 14.0
        script: |
          echo "🛠 Ensuring Podfile platform..."
          if [ ! -f "ios/Podfile" ]; then
            cd ios
            pod init
            cd ..
          fi
          sed -i '' 's/platform :ios.*/platform :ios, '\''14.0'\''/' ios/Podfile || echo "platform :ios, '14.0'" >> ios/Podfile
          cat ios/Podfile

      - name: Install CocoaPods dependencies
        script: |
          echo "📦 Installing pods..."
          cd ios
          pod repo update || true
          pod install || true
          cd ..

      - name: Enable automatic code signing
        script: |
          echo "🔐 Configuring automatic code signing..."
          automatic-code-signing use-auto-signing \
            --team-id $APP_STORE_TEAM_ID \
            --bundle-id $BUNDLE_ID

      - name: Build iOS IPA for TestFlight
        script: |
          echo "🍎 Building iOS IPA..."
          mkdir -p ios
          cat > ios/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>teamID</key>
              <string>$APP_STORE_TEAM_ID</string>
              <key>compileBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF

          flutter build ios --release --no-codesign
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner \
            --export-options-plist ios/exportOptions.plist

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - "Ibraheemakin201@gmail.com"
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
