workflows:
  build_ios:
    name: Build iOS for TestFlight (Automatic Signing)
    environment:
      groups:
        - appstore_credentials          # <-- your API-key variables
      vars:
        APP_NAME: "LeisureRyde"
        BUNDLE_ID: "com.leisureryde.ryde"
        APP_STORE_TEAM_ID: "S8LF4BM9D3"   # <-- you already have this as apple_team_id
      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      # --------------------------------------------------------------
      # 1. Flutter deps
      # --------------------------------------------------------------
      - name: Flutter clean & get
        script: |
          flutter clean
          flutter pub get

      # --------------------------------------------------------------
      # 2. Force iOS 14.0 in Podfile **and** in the Xcode project
      # --------------------------------------------------------------
      - name: Set iOS deployment target to 14.0
        script: |
          # ---- Podfile ------------------------------------------------
          PODFILE=ios/Podfile
          if ! grep -q "platform :ios" "$PODFILE"; then
            echo "Adding platform line"
            sed -i '' '1s/^/platform :ios, "14.0"\n/' "$PODFILE"
          else
            sed -i '' 's/platform :ios.*/platform :ios, "14.0"/' "$PODFILE"
          fi

          # ---- Info.plist (Xcode project) -----------------------------
          PLIST=ios/Runner/Info.plist
          /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 14.0" "$PLIST" \
            || /usr/libexec/PlistBuddy -c "Add :MinimumOSVersion string 14.0" "$PLIST"

          # ---- Verify -------------------------------------------------
          echo "Podfile platform:"
          grep "platform :ios" "$PODFILE"
          echo "Info.plist MinimumOSVersion:"
          /usr/libexec/PlistBuddy -c "Print :MinimumOSVersion" "$PLIST"

      # --------------------------------------------------------------
      # 3. CocoaPods
      # --------------------------------------------------------------
      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install

      # --------------------------------------------------------------
      # 4. Build the archive (automatic signing)
      # --------------------------------------------------------------
      - name: Archive with automatic signing
        script: |
          # exportOptions.plist (you already create it later – we reuse it)
          cat > ios/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>teamID</key><string>$APP_STORE_TEAM_ID</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          EOF

          flutter build ios --release --no-codesign

          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -configuration Release \
                     -archivePath $CM_BUILD_DIR/Runner.xcarchive \
                     DEVELOPMENT_TEAM=$APP_STORE_TEAM_ID \
                     CODE_SIGN_STYLE=automatic \
                     archive

          xcodebuild -archivePath $CM_BUILD_DIR/Runner.xcarchive \
                     -exportArchive \
                     -exportOptionsPlist ios/exportOptions.plist \
                     -exportPath $CM_BUILD_DIR/ipa

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - "Ibraheemakin201@gmail.com"
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true