workflows:
  ios-testflight:
    name: iOS to TestFlight (Auto-Sign)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      groups:
        - appstore_credentials
      vars:
        BUNDLE_ID: "com.leisureryde.ryde"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        IOS_DEPLOYMENT_TARGET: "14.0"
        APPLE_TEAM_ID: "S8LF4BM9D3"  # âœ… Replace with your actual Apple Team ID
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Get Flutter dependencies
        script: |
          echo "ðŸ“¦ Fetching Flutter dependencies..."
          flutter clean || true
          flutter pub get

      - name: Patch Podfile for iOS 14.0
        script: |
          echo "ðŸ›  Patching Podfile for iOS 14.0..."
          PODFILE="ios/Podfile"

          if [ ! -f "$PODFILE" ]; then
            cd ios && pod init && cd ..
          fi

          # Append post_install block safely
          cat <<'RUBY' >> "$PODFILE"

  post_install do |installer|
  installer.pods_project.targets.each do |target|
  flutter_additional_ios_build_settings(target)
  target.build_configurations.each do |config|
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
  end
  end
  end
  RUBY
  echo "âœ… Podfile patched successfully."

- name: Install CocoaPods
  script: |
    echo "ðŸ“¦ Installing CocoaPods..."
    cd ios
    pod repo update || true
    pod install --verbose
    cd ..

- name: Set iOS Deployment Target
  script: |
    echo "ðŸ“± Setting iOS deployment target..."
    /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 14.0" ios/Runner/Info.plist 2>/dev/null \
      || /usr/libexec/PlistBuddy -c "Add :MinimumOSVersion string 14.0" ios/Runner/Info.plist

- name: Archive and Export IPA
  script: |
    echo "ðŸ— Building iOS archive and exporting IPA..."
    ARCHIVE_PATH="$CM_BUILD_DIR/Runner.xcarchive"
    IPA_PATH="$CM_BUILD_DIR/ipa"
    
    cat > ios/exportOptions.plist <<EOF
  <?xml version="1.0" encoding="UTF-8"?>
  <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
  <dict>
  <key>method</key><string>app-store</string>
  <key>signingStyle</key><string>automatic</string>
  <key>teamID</key><string>$APPLE_TEAM_ID</string>
  <key>uploadSymbols</key><true/>
  <key>compileBitcode</key><false/>
  </dict>
  </plist>
  EOF
  
  xcodebuild -workspace "ios/$XCODE_WORKSPACE" \
  -scheme "$XCODE_SCHEME" \
  -archivePath "$ARCHIVE_PATH" \
  DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
  CODE_SIGN_STYLE=Automatic \
  archive | xcpretty
  
  xcodebuild -exportArchive \
  -archivePath "$ARCHIVE_PATH" \
  -exportOptionsPlist ios/exportOptions.plist \
  -exportPath "$IPA_PATH" \
  -allowProvisioningUpdates | xcpretty

artifacts:
  - $CM_BUILD_DIR/ipa/*.ipa

publishing:
  email:
    recipients:
      - "Ibraheemakin201@gmail.com"
a
  app_store_connect:
    api_key: $APP_STORE_CONNECT_PRIVATE_KEY
    key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
    issuer_id: $APP_STORE_CONNECT_ISSUER_ID
    submit_to_testflight: true
