// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3i3yY36cSYKFK8NHQHpOxwDULFz__6Sk',
    appId: '1:785199365327:android:99b6d817bbfe36eb3c8bba',
    messagingSenderId: '785199365327',
    projectId: 'leisureryde-3ca0b',
    databaseURL: 'https://leisureryde-3ca0b-default-rtdb.firebaseio.com',
    storageBucket: 'leisureryde-3ca0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQ_BEZ5TqMnLds27XtGZRm6V8iMRHzV8',
    appId: '1:785199365327:ios:9c5881d91131bfb43c8bba',
    messagingSenderId: '785199365327',
    projectId: 'leisureryde-3ca0b',
    databaseURL: 'https://leisureryde-3ca0b-default-rtdb.firebaseio.com',
    storageBucket: 'leisureryde-3ca0b.firebasestorage.app',
    iosBundleId: 'com.leisureryde.ride',
  );
}
